OCI_REALTIME_SPEECH_URl="wss://realtime.aiservice.us-phoenix-1.oci.oraclecloud.com/ws/transcribe/stream"
OCI_REALTIME_SPEECH_LANGUAGE_CODE="en-US"
OCI_REALTIME_SPEECH_MODEL_DOMAIN='GENERIC'
OCI_REALTIME_SPEECH_PARTIAL_SILENCE_THRESHOLD_IN_MS=0
OCI_REALTIME_SPEECH_FINAL_SILENCE_THRESHOLD_IN_MS=1000
OCI_REALTIME_SPEECH_SHOULD_IGNORE_INVALID_CUSTOMIZATIONS=False

OCI_COMPARTENT_ID="YOUR_OCI_COMPARTMENT_OCID"

OCI_AUTH_FILE_LOCATION="~/.oci/config"
OCI_AUTH_PROFILE_NAME="DEFAULT"